name: ReviewBuddy

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ReviewBuddy
        uses: l1v0n1/ReviewBuddy@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .reviewbuddy.yml 